# Generated by Django 3.2.8 on 2022-03-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('disco', models.CharField(max_length=255)),
                ('memoria', models.CharField(max_length=255)),
                ('vcpu', models.CharField(max_length=255)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ambiente')),
                ('contexto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.contexto')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.dominio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa')),
                ('externo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.externo')),
                ('ferramenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ferramenta')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.operacional')),
                ('pci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pci')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('mascara', models.CharField(max_length=50)),
                ('gateway', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServidorUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.servidor')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.url')),
            ],
        ),
        migrations.AddField(
            model_name='servidor',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.versao'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='vlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.vlan'),
        ),
    ]
